### ISSUE TITLE
Using survival fonction to compute p-values

### ISSUE THREAD

**Issue by cmaumet** [JLefortBesnard/SDMA#1]
Hi @JLefortBesnard!

For a coming update, I would suggest to use `sf` instead of `1-cdf` when computing p-values, as in https://github.com/JLefortBesnard/SDMA/blob/main/scripts/MA_estimators.py#L55
	
This can be in particular useful for very small p-values (when cdf is close to 1) to avoid getting p-values equal to zero.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.norm.html

**Comment by JLefortBesnard** [comment]
Updated in commit [c3c9dee](https://github.com/JLefortBesnard/SDMA/commit/c3c9dee35f2f303f38b459adfe0d493c6ada8d02)
